# Generated by Django 4.0.2 on 2022-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('salaire', models.FloatField(max_length=10)),
                ('tel', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
    ]
